### ISSUE TITLE
Weird behavior when using ItemSeparatorComponent props

### ISSUE THREAD

**Issue by theodelebarre** [jemise111/react-native-swipe-list-view#243] opened 2018-10-19 09:41 UTC
Hi there,

Found out a weird bug when using ItemSeparatorComponent props.
The 7th item displayed in the list doesn't have the separator, tried to add and remove some, it's always the 7th.
This is my separator, nothing unusual, it is below every item except the 7th.
ItemSeparatorComponent={() => (
            <View
              style={{
                width: "100%",
                height: 0.5,
                backgroundColor: Colors.grey_2,
                marginLeft: Metrics.screenWidth * 0.04
              }}
            />
          )}

Thanks in advance for your help! And thanks a lot for this component!

**Comment by jemise111** [comment] 2018-11-24 02:03
Hey @theodelebarre I plugged an ItemSeparatorComponent into the example with this repo and I'm not seeing any problems with my list of 20 items:

![image](https://user-images.githubusercontent.com/4265163/48963569-a0487b80-ef5a-11e8-9caf-977b5db9a54f.png)

Sorry but I really don't think it's an issue with this Component, as I pass all props to the underlying FlatList and there's definitely nothing special that I'm doing with the 7th item in the list. I can try to dig deeper if you could provide some more code or better yet a reproducible standalone example..

Thanks!

**Comment by jemise111** [comment] 2019-05-19 01:23
Closing this issue, please reopen if it is still a problem, thanks!

**Closed by jemise111** 2019-05-19 01:23 UTC

**Comment by meetjpatel** [comment] 2020-09-30 12:18
In case, anyone still facing this issue, It may be because of the background color of <SwipeListView>'s parent view.
So you could just add contentContainerStyle={{backgroundColor: '#FFF'(whatever the color of your list item is)}} to <SwipeListView> and it should be fixed.
