### ISSUE TITLE
swipeGestureEnded is not called

### ISSUE THREAD

**Issue by andrey-shostik** [jemise111/react-native-swipe-list-view#523] opened 2020-10-27 00:20 UTC
**Describe the bug**
I would like to add custom logic when swipe is end, but the prop `swipeGestureEnded` doesn't work for SwipeRow component

**To Reproduce**
Just pass `swipeGestureEnded` prop to SwipeRow, and the `swipeGestureEnded` never be called. I was debugging  and no matter if I pass `swipeGestureEnded` or no the `swipeGestureEnded` comes for SwipeRow component, it looks like it overwriting by a new one which is not mine what is strange.

**Screenshots**
if you don't pass `swipeGestureEnded` the console will print function instead of undefined as it should be. If you pass `swipeGestureEnded` you will see the same, but the function is not that I have passed
![image](https://user-images.githubusercontent.com/13626849/97242341-4c0c3d00-17fc-11eb-9286-ec5aa2a01414.png)

**Environment (please complete the following information):**
 - OS: IOS 11 - 14.0
 - RNSLV Version: 3.2.5
 - RN Version: 0.63.3

During my experimentations, I added handling `swipeGestureEnd` instead of `swipeGestureEnded` and  accordingly passed `swipeGestureEnd` prop, and after that I got it worked

**Comment by jemise111** [comment] 2020-10-27 14:27
Hi @andrey-shostik I just double checked this on my machine, it's most certainly working as intended. If you look through the entire codebase you will not find any mention of `swipeGestureEnd`

Since you have this working can I close this issue?


```
export default function StandalonSwipeRow() {
    return (
        <View style={styles.container}>
            <View style={styles.standalone}>
                <SwipeRow
                    swipeGestureEnded={() =>
                        console.log('swipe gesture is over')
                    }
                    leftOpenValue={75}
                    rightOpenValue={-75}
                >
                    <View style={styles.standaloneRowBack}>
```


![gesture mov](https://user-images.githubusercontent.com/4265163/97315297-94485100-1836-11eb-9e77-291dbfdb50b7.gif)

**Comment by andrey-shostik** [comment] 2020-10-27 15:26
@jemise111 Hi. I have checked with your swipe list example `per_row_config.js` and there actually some issue exist. I'm attaching video https://drive.google.com/file/d/1e4TuPK6pNZD4nB_82VEaX7vNqGxueUNS/view

**Comment by jemise111** [comment] 2020-10-28 13:45
Hi @andrey-shostik okay I see what is going on now. You are referring to cases when you use a `SwipeListView` **and** a `SwipeRow`. In these cases you should pass the prop to the `SwipeListView` instead of the `SwipeRow`, and that should fix your issues

**Comment by andrey-shostik** [comment] 2020-10-28 15:13
@jemise111 Thank you, it helped me

**Comment by jemise111** [comment] 2020-10-28 15:24
Excellent, thanks

**Closed by jemise111** 2020-10-28 15:24 UTC
