### ISSUE TITLE
swipe broken when continously swipe rows in ios

### ISSUE THREAD

**Issue by Jagadeesh-Govindaraj** [jemise111/react-native-swipe-list-view#140] opened 2017-07-31 06:00 UTC
when open continually swipe rows  swipe got broken and rows are not able to swipe, its only occurs in real device of ios (all devices)

Steps to reproduce
At least swipe 7times on diffrent postion like first scroll a listview up and down and next swipe a rows left to right ,now rows are get jumped in every swipe.and not opened the rows.

**Comment by jemise111** [comment] 2017-10-22 08:22
Hey @Jagadeesh-Govindaraj thanks for the report! I'm almost positive this is a dupe of issue #34 which currently doesn't have a fix. Going to close this but it's being worked on

**Closed by jemise111** 2017-10-22 08:22 UTC
