### ISSUE TITLE
HiddenItem become visible when parent component is unmounting

### ISSUE THREAD

**Issue by a-klimashevsky** [jemise111/react-native-swipe-list-view#318] opened 2019-07-16 15:02 UTC
react-native-swipe-list-view version: 1.5 and above (2.0.0 also)
react-native version 0.59.10
steps to reproduce:
1) open screen with list contained HiddenItem
2) close list

Result: HiddenItem is visible for all rows for a short period of time
Expected Result: screen goes off normally.

bug is not reproduced at react-native version 0.59.8 and below.

**Comment by jemise111** [comment] 2019-08-18 15:57
Hey @a-klimashevsky sorry but I need some more context here. I've tried to reproduce this by having the List rendered on the screen, and then by clicking a button I stop rendering it but it is appearing/disappearing correctly and I'm not seeing what you're talking about.

Could you provide a full reproducible example? Thanks!

**Comment by ankhzet** [comment] 2019-08-30 14:11
@a-klimashevsky I guess you referring to updates to react-native's way of handling opacity on android (since 0.60, i guess?..). It's an issue with screen transitioning (due to how opacity is now handled): when transition kicks-in, unmounted screen receives partial opacity, which is then inherited by all its child nodes, including list rows, so swipe actions layer can be seen through upper layer - item row itself.

I used a workaround (https://github.com/jemise111/react-native-swipe-list-view/issues/182#issuecomment-521675141) - turn on `needsOffscreenAlphaCompositing` for a parent view of the list when screen is in 'unfocused' state (is transitioning f.e.). It may cause performance drops while screen transition is animated on a large lists, but I haven't noticed much of a performance drop on my dev devices.

**Comment by jemise111** [comment] 2020-02-11 18:37
@ankhzet Thanks for your response! This sounds like a great workaround, given the hierarchy of components in the swiperow. Closing as resolved

**Closed by jemise111** 2020-02-11 18:37 UTC
