### ISSUE TITLE
can't open item

### ISSUE THREAD

**Issue by DominicHan** [jemise111/react-native-swipe-list-view#143] opened 2017-08-07 12:26 UTC
When I scroll to bottom, delete any one in the screen. After that I can't open any item of the screens.

**Comment by dotcink** [comment] 2017-08-29 06:56
Same problem.

**Comment by dotcink** [comment] 2017-08-29 09:49
Seems that when you delete an item at the bottom(iOS), the ListView would scroll up a little bit and over its bottom, then unless you restore the unexpected scroll state the Row will never respond touch event.

I resolve it by force `scrollToEnd()` when `yScrollOffset >= contentHeight - layoutHeight` in `onContentSizeChange()`.

```
onLayout={e => this.layoutHeight = e.nativeEvent.layout.height}
onContentSizeChange={(w, h) => this.contentHeight = h}
onScroll={e => this.yScrollOffset = e.nativeEvent.contentOffset.y}
```

ps. Same issue as #109

**Comment by jemise111** [comment] 2017-10-22 08:26
Hey @DominicHan thanks for the report. @dotcink is right that this is a dupe of #109. Currently working on a fix but don't have anything yet. Thanks for the helpful comments, will look into them as possible solutions.

Going to close this issue though and track it in the original, thanks!

(sorry for the late response!)

**Closed by jemise111** 2017-10-22 08:26 UTC
