### ISSUE TITLE
Sometimes can not swipe in iOS

### ISSUE THREAD

**Issue by Fox-3394** [jemise111/react-native-swipe-list-view#147] opened 2017-09-05 02:57 UTC
Hi @jemise111 @levitanong 
Thank you for this awsome plugin.
But there is a bug in iOS that should be fixed: when I swipe in horizontal, it works OK. But when I try to swipe down 45 degree then the bug appears, it will not allow to swipe horizontal anymore.

This bug is only appear in iOS, in Android this plugin works fine.

![bug_swipe_ios-_online-video-cutter com_](https://user-images.githubusercontent.com/25562336/30043544-3786749e-9222-11e7-818a-abcfa9f8a395.gif)

**Comment by whaoran** [comment] 2017-09-09 08:35
I have the same problem.

**Comment by csath** [comment] 2017-09-11 06:51
Same here.

**Comment by Abdisalan** [comment] 2017-09-12 19:34
I also have this problem. bump.

**Comment by niocncn** [comment] 2017-09-19 22:25
same problem

**Comment by bounddog** [comment] 2017-09-20 10:01
why don't try the nativebase.io? it has such feature and worked perfectly.

**Comment by jemise111** [comment] 2017-10-22 08:47
Hey @Fox-3394 thanks for the report. This is a dupe of #34, currently working on it but don't have a fix yet. Going to close this and track in the other issue, sorry for the delay in responding!

@bounddog nativebase's SwipeRow component is almost an exact copy paste of this one, right down to the comments, just FYI :)

**Closed by jemise111** 2017-10-22 08:47 UTC

**Comment by Fox-3394** [comment] 2017-10-23 17:29
@jemise111 Thank for your feedback.
