### ISSUE TITLE
Sometimes can not be closed when sliding

### ISSUE THREAD

**Issue by juxiaowei** [jemise111/react-native-swipe-list-view#117] opened 2017-04-13 03:57 UTC
Sometimes can not be closed when sliding

**Comment by juxiaowei** [comment] 2017-04-13 03:57
It is recommended to increase the shutdown function

**Comment by juxiaowei** [comment] 2017-04-13 05:44
@ajma

**Comment by jemise111** [comment] 2017-04-13 13:22
Hey @juxiaowei, what do you mean by "can not be closed"? Do you have a way to repro this, or some code that's showing the buggy behavior?

**Comment by juxiaowei** [comment] 2017-04-14 13:30
@jemise111 
Sometimes the slide will bounce back

**Comment by nonotest** [comment] 2017-06-17 04:55
@juxiaowei what do you mean by "It is recommended to increase the shutdown function"
I am also experiencing this issue. Can try to take a look this weekend

**Comment by cblavier** [comment] 2017-06-29 10:06
Any update on this?

 I'm experiencing the same issue while opening or closing menus : sometime it become really hard to open / close it and I have to swipe really fast.

The issue is totally random, and can only be reproduced on a real device (iPhone)

**Comment by jemise111** [comment] 2017-10-20 18:48
Going to close as this has been inactive for a while. I strongly suspect this is a dupe of #34 or #109

**Closed by jemise111** 2017-10-20 18:48 UTC
